package progress

import (
	"fmt"
	"strings"

	"github.com/mesa-studio/codemod-tally/internal/state"
)

// Generate produces a markdown progress file from state.
// The file is read-only — updated exclusively by `codemod-tally scan`.
func Generate(s *state.State) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s — Progress\n\n", s.Recipe)
	fmt.Fprintf(&b, "> Generated by `codemod-tally scan`. Do not edit manually.\n")
	fmt.Fprintf(&b, "> Last scan: %s | %d/%d done | %d remaining\n\n",
		s.LastScan.Format("2006-01-02 15:04"),
		s.Done(), len(s.Occurrences), s.Remaining(),
	)

	var remaining, done []state.Occurrence
	for _, o := range s.Occurrences {
		if o.Status == state.StatusTodo {
			remaining = append(remaining, o)
		} else {
			done = append(done, o)
		}
	}

	fmt.Fprintf(&b, "## Remaining (%d)\n\n", len(remaining))
	for _, o := range remaining {
		fmt.Fprintf(&b, "- [ ] `%s:%d` — `%s`\n", o.File, o.Line, o.Content)
	}

	fmt.Fprintf(&b, "\n## Done (%d)\n\n", len(done))
	for _, o := range done {
		fmt.Fprintf(&b, "- [x] `%s:%d` — `%s`\n", o.File, o.Line, o.Content)
	}

	return b.String()
}
